name: hr_application
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  glassmorphism_widgets: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/  
